### ISSUE TITLE
Maintain compatibility with old links on new site

### ISSUE THREAD

**Issue by seproDev** [Aegisub/aegisite#14]
Ideally we would be able to redirect old URLs to new ones as to not break links.
Some DNS providers allow setting fake `REDIRECT` records that could be used to setup redirects like this:

| Old  | New |
| ------------- | ------------- |
| `www.aegisub.org` | `aegisub.org` (alternatively CNAME) |
| `docs.aegisub.org/*` | `aegisub.org/docs/*` |
| `blog.aegisub.org/*` | `aegisub.org/blog/*` |
| `ftp.aegisub.org` | `aegisub.org/downloads/` (?) |
| `devel.aegisub.org` | `github.com/Aegisub/Aegisub` |

(* meaning with the path being forwarded)

Speaking of DNS records, looking at the NS records `aegisub.org` seems to be using [GratisDNS](https://web.gratisdns.dk/) as a DNS provider which will be [shutting down by the end of the month](https://help.one.com/hc/en-us/articles/4417467033489-Ofte-stillede-sp%C3%B8rgsm%C3%A5l-om-migreringen-fra-GratisDNS-til-one-com). Customers can migrate to [one.com](https://www.one.com/en/), but maybe this is a good time to re-evaluate providers.

If redirects at the DNS provider level are not possible, we could either point all subdomains at the site and use some javascript to redirect to the correct page or use something like [cloudflare workers](https://developers.cloudflare.com/workers/examples/redirect/) to make the redirects.
Edit: if we are hosting on our own hardware anyway doing those redirects in the nginx config would be much better than using javascript.

The actual forwards on the site (blog URLs differ completely and docs URLs are not capitalized by hugo) can be handled with [hugo aliases](https://gohugo.io/content-management/urls/#aliases). Once the switch to hugo is done and the DNS situation is figured out I'll make a PR adding the aliases.

**Comment by seproDev** [comment]
Oh yeah the `updates.aegisub.org` subdomain also needs to point somewhere. Though redirects won't work here as Aegisub [expects a status code of 200](https://github.com/Aegisub/Aegisub/blob/3.2/src/dialog_version_check.cpp#L311).
Also no Github Pages since Aegisub doesn't support HTTPS.

There should probably be an issue somwhere talking about how the update infastrucutre is going to work.

**Comment by CoffeeFlux** [comment]
For the redirects, I'm not sure what the provider supports - I'll have to ask jfs. `ftp.aegisub.org` will probably just be moved to a fixed downloads page like you guessed, since I have no desire to run a public FTP server. The updater situation is slightly awkward and one of the last things I'd need to iron out before releasing a stable. If you ping me on Discord, I can explain.
