### ISSUE TITLE
Installing and using Aegisub (macos)

### ISSUE THREAD

**Issue by wakoxxkubo** [Aegisub/aegisite#46]
I tried installing and then opening Aegisub on my mac but it said I couldn't open it. How can I open it without this message? (First time user/installing)

Aegisub-3.4.0

<img width="555" alt="Screenshot 2024-12-20 at 11 33 32 PM" src="https://github.com/user-attachments/assets/aa42a425-002e-42ed-911f-1f32efdebcee" />

(Apologies if this is not the place to post this but I didn't know where to.)

**Comment by seproDev** [comment]
This is sadly an issue with Apple not allowing CoffeeFlux to give then $ 100/year. See the release blog post for more details: https://aegisub.org/blog/aegisub-3.4.0-released/#macos

**Comment by wakoxxkubo** [comment]
Thank you for your response & directing me to the info. I hope it can get figured out and I'll try to email the apple contact written on the page.
